#!/usr/bin/env python3
"""Clean a Claude Code session JSONL into a compact JSON conversation log.

Goal: a *distilled* conversation to feed into other AI sessions — user intent
and outcomes, without the raw-output tokens that pollute a fresh context.

Tool calls are triaged by name into tiers (this is the "tiered" branch):
- KEEP OUTPUT: subagent results (Agent/Task) are kept in full — they are real
  outcomes. (Async launch stubs carry no output, so they collapse to a line.)
- DECISION: AskUserQuestion answers -> "[decision] <question> → <answer>".
- KEEP LINE: Edit/Write, mutating Bash, Skill (name only), web, unknown tools ->
  one `actions` line; errors appended as "… → error: ...". Output dropped.
- COLLAPSE: read-only tools (Read/Grep/Glob, read-only Bash), browser UI,
  ToolSearch, ctx_* -> consecutive runs coalesce to "browser ×42". Output dropped.
- DROP: session-management tools (Task*, ScheduleWakeup, PushNotification,
  mark_chapter, Enter/ExitWorktree) emit nothing at all.

Always dropped: raw tool output, assistant `thinking`, and harness boilerplate
(skill-content loads, <command-*>, <system-reminder>, <task-notification>,
interrupts, /loop sentinels, sandbox caveats). Skill *content* is dropped; the
Skill call keeps only the skill name.

Output schema:
{
  "source": "<file name>",
  "messages": [
    {"role": "user", "text": "..."},                       # prose / [decision]
    {"role": "assistant", "text": "..."},                  # prose
    {"role": "assistant", "actions": ["Edit a.py", "browser ×42", ...]},
    {"role": "subagent", "text": "<full agent report>"},
    ...
  ]
}

Usage: clean_claude_session.py SRC.jsonl DST.json
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

IDE_FILE_RE = re.compile(r"^<ide_opened_file>.*?</ide_opened_file>\s*", re.DOTALL)
ERR_TAG_RE = re.compile(r"</?tool_use_error>")
MAX = 140  # one-liner truncation width

NOISE_PREFIXES = (
    "Base directory for this skill:",
    "<command-message", "<command-name", "<command-args",
    "<local-command-stdout", "<local-command-stderr", "<local-command-caveat",
    "<env_context", "<environment_context", "<system-reminder", "<task-notification",
    "[SYSTEM NOTIFICATION - NOT USER INPUT]", "<bash-stdout", "<bash-stderr",
    "[Request interrupted by user", "<<autonomous-loop",
    "Caveat: The messages below were generated by the user while running local commands",
)

FILE_TOOLS = {"Edit", "Write", "Read", "NotebookEdit", "MultiEdit"}
SALIENT_KEYS = ("command", "prompt", "query", "url", "path", "file_path", "message", "skill")

# --- tool tiers (matched on the bare tool name, mcp__server__ prefix stripped) ---
SUBAGENT_TOOLS = {"Agent", "Task"}
DROP_TOOLS = {  # session-management plumbing: emit nothing
    "TaskCreate", "TaskUpdate", "TaskList", "TaskGet", "TaskOutput", "TaskStop",
    "ScheduleWakeup", "PushNotification", "mark_chapter",
    "EnterWorktree", "ExitWorktree", "spawn_task", "dismiss_task", "read_widget_context",
}
GROUP_LABEL = {"read": "read/grep", "search": "ToolSearch", "browser": "browser", "ctx": "ctx", "bash": "bash(ro)"}
BROWSER_HINTS = ("computer", "navigate", "read_page", "find", "form_input", "get_page_text",
                 "read_console_messages", "read_network_requests", "tabs_context_mcp",
                 "tabs_create_mcp", "tabs_close_mcp", "resize_window", "gif_creator", "screenshot")
RO_BASH = {"ls", "cat", "pwd", "echo", "head", "tail", "which", "type", "stat", "wc", "tree",
           "file", "rg", "grep", "fd", "find", "eza", "bat", "df", "du", "env", "printenv",
           "date", "whoami", "uname"}  # sed/awk excluded: -i mutates
RO_GIT = {"status", "log", "diff", "show", "branch", "remote", "rev-parse", "describe", "blame"}


def short(s) -> str:
    s = " ".join(str(s).split())
    return s if len(s) <= MAX else s[: MAX - 1] + "…"


def clean_name(name: str) -> str:
    return name.split("__")[-1] if name.startswith("mcp__") else name


def summarize_tool(name: str, inp) -> str | None:
    """One compact line for a tool call, or None only for AskUserQuestion."""
    inp = inp if isinstance(inp, dict) else {}
    if name == "AskUserQuestion":
        return None
    if name in FILE_TOOLS:
        return f"{name} {inp.get('file_path') or inp.get('notebook_path') or '?'}"
    if name == "Skill":
        return f"Skill {inp.get('skill', '?')}"  # name only; skill body is dropped as noise
    disp = clean_name(name)
    if inp.get("description"):
        return f"{disp}: {short(inp['description'])}"
    for k in SALIENT_KEYS:
        if inp.get(k):
            return f"{disp}: {short(inp[k])}"
    return disp


def collapse_group(name: str):
    if name in ("Read", "Grep", "Glob", "LS", "NotebookRead"):
        return "read"
    if name == "ToolSearch":
        return "search"
    if "chrome" in name or "Browser" in name or name.endswith(BROWSER_HINTS):
        return "browser"
    if "ctx_" in name:
        return "ctx"
    return None


def bash_readonly(inp) -> bool:
    # ponytail: leading-token heuristic. Compound/piped read-only cmds fall to
    # KEEP-LINE (harmless). Upgrade to a real parser only if bash dominates residual.
    cmd = (inp or {}).get("command", "").strip()
    parts = cmd.split()
    if not parts:
        return False
    if parts[0] == "git":
        return len(parts) > 1 and parts[1] in RO_GIT
    return parts[0] in RO_BASH


def classify(name: str, inp):
    """Return (kind, group, label). kind in {drop, skip, subagent, collapse, line}."""
    if clean_name(name) in DROP_TOOLS:
        return ("drop", None, None)
    if name == "AskUserQuestion":
        return ("skip", None, None)
    label = summarize_tool(name, inp)
    if name in SUBAGENT_TOOLS:
        return ("subagent", None, label)
    if name == "Bash":
        return ("collapse", "bash", label) if bash_readonly(inp) else ("line", None, label)
    g = collapse_group(name)
    if g:
        return ("collapse", g, label)
    return ("line", None, label)


def extract_text(content) -> str:
    if isinstance(content, str):
        return content.strip()
    if not isinstance(content, list):
        return ""
    chunks = [i.get("text", "") for i in content if isinstance(i, dict) and i.get("type") == "text"]
    return "\n".join(c for c in chunks if c).strip()


def tool_use_blocks(content) -> list[dict]:
    if not isinstance(content, list):
        return []
    return [b for b in content if isinstance(b, dict) and b.get("type") == "tool_use"]


def is_only_tool_result(content) -> bool:
    if not isinstance(content, list):
        return False
    has_any = False
    for item in content:
        if not isinstance(item, dict):
            continue
        has_any = True
        if item.get("type") != "tool_result":
            return False
    return has_any


def result_text(block: dict) -> str:
    c = block.get("content")
    if isinstance(c, list):
        return "\n".join(x.get("text", "") for x in c if isinstance(x, dict)).strip()
    return str(c or "").strip()


def error_map(content) -> dict:
    out = {}
    if not isinstance(content, list):
        return out
    for b in content:
        if not (isinstance(b, dict) and b.get("type") == "tool_result" and b.get("is_error")):
            continue
        out[b.get("tool_use_id")] = short(ERR_TAG_RE.sub("", result_text(b)))
    return out


def decisions(record: dict) -> list[str]:
    tur = record.get("toolUseResult")
    answers = tur.get("answers") if isinstance(tur, dict) else None
    if not isinstance(answers, dict):
        return []
    return [f"{q} → {a}" for q, a in answers.items()]


def is_noise(text: str) -> bool:
    return not text or any(text.startswith(p) for p in NOISE_PREFIXES)


def distill(src: Path) -> dict:
    records = []
    with src.open(encoding="utf-8") as f:
        for raw in f:
            try:
                records.append(json.loads(raw))
            except Exception:
                continue

    # tool_use id -> name, and errors, in one sweep
    id_name: dict = {}
    errors: dict = {}
    for d in records:
        m = d.get("message")
        if not isinstance(m, dict):
            continue
        errors.update(error_map(m.get("content")))
        for b in tool_use_blocks(m.get("content")):
            id_name[b.get("id")] = b.get("name", "")

    # subagent tool_use id -> full result text (sync only; async launch stubs skipped)
    sub_results: dict = {}
    for d in records:
        m = d.get("message")
        if not isinstance(m, dict):
            continue
        for b in (m.get("content") if isinstance(m.get("content"), list) else []):
            if not (isinstance(b, dict) and b.get("type") == "tool_result"):
                continue
            tid = b.get("tool_use_id")
            if id_name.get(tid) not in SUBAGENT_TOOLS:
                continue
            txt = result_text(b)
            tur = d.get("toolUseResult")
            is_async = (isinstance(tur, dict) and tur.get("isAsync")) or txt.startswith("Async agent launched")
            if txt and not is_async:
                sub_results[tid] = txt

    messages: list[dict] = []
    run: list[tuple] = []  # pending (group, label); group None = non-coalescing

    def flush():
        if not run:
            return
        acts, i = [], 0
        while i < len(run):
            g, label = run[i]
            if g is not None:
                j = i
                while j < len(run) and run[j][0] == g:
                    j += 1
                cnt = j - i
                acts.append(label if cnt == 1 else f"{GROUP_LABEL[g]} ×{cnt}")
                i = j
            else:
                acts.append(label)
                i += 1
        messages.append({"role": "assistant", "actions": acts})
        run.clear()

    for d in records:
        if d.get("type") not in ("user", "assistant"):
            continue
        msg = d.get("message")
        if not isinstance(msg, dict):
            continue
        role = msg.get("role")
        if role not in ("user", "assistant"):
            continue
        content = msg.get("content", "")

        if role == "user":
            decs = decisions(d)
            if decs:
                flush()
                for line in decs:
                    messages.append({"role": "user", "text": f"[decision] {line}"})
                continue
            # subagent result (full)
            hit = None
            if isinstance(content, list):
                for b in content:
                    if isinstance(b, dict) and b.get("type") == "tool_result" and b.get("tool_use_id") in sub_results:
                        hit = b.get("tool_use_id")
                        break
            if hit:
                flush()
                messages.append({"role": "subagent", "text": sub_results[hit]})
                continue
            if is_only_tool_result(content):
                continue  # tool echo between calls — do NOT flush, keeps runs intact
            text = IDE_FILE_RE.sub("", extract_text(content)).strip()
            if text and not is_noise(text):
                flush()
                messages.append({"role": "user", "text": text})
            continue

        # assistant
        text = extract_text(content)
        if text:
            flush()
            messages.append({"role": "assistant", "text": text})
        for b in tool_use_blocks(content):
            kind, group, label = classify(b.get("name", ""), b.get("input"))
            if kind in ("drop", "skip"):
                continue
            if kind != "collapse" and b.get("id") in errors:
                label += f"  → error: {errors[b['id']]}"
            run.append((group if kind == "collapse" else None, label))
    flush()

    return {"source": src.name, "messages": messages}


def main() -> None:
    src, dst = Path(sys.argv[1]), Path(sys.argv[2])
    out = distill(src)
    dst.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {dst} ({dst.stat().st_size:,} bytes, {len(out['messages'])} messages)")


if __name__ == "__main__":
    main()
