#!/usr/bin/env python3
"""Clean a Claude Code session JSONL into a compact JSON conversation log.

Goal: a *distilled* conversation to feed into other AI sessions — user intent
and outcomes, without the raw-output tokens that pollute a fresh context.

Three buckets:
- KEEP verbatim: real user prose, real assistant prose, and user *decisions*
  (AskUserQuestion answers — captured from the record's `toolUseResult.answers`
  as a "[decision] <question> → <answer>" line, since they ARE intent).
- REDUCE to one line: each assistant tool call becomes a short `actions` entry
  ("Bash: run tests", "Edit src/foo.py"); if that call errored, the error is
  appended ("… → error: ..."). Successful outcomes are implied.
- DROP: raw tool output (non-error tool_result bodies), assistant `thinking`,
  and harness boilerplate (skill loads, <command-*>, <system-reminder>,
  <task-notification>, interrupts, /loop sentinels, sandbox caveats).

Output schema:
{
  "source": "<source file name>",
  "messages": [
    {"role": "user", "text": "..."},
    {"role": "assistant", "text": "...", "actions": ["Bash: run tests", ...]},
    ...
  ]
}
`text` is omitted when empty; `actions` is omitted when there were no tool calls.

Also strips leading <ide_opened_file>...</ide_opened_file> wrappers from user
messages while keeping the real prose that follows.

Usage: clean_claude_session.py SRC.jsonl DST.json
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

IDE_FILE_RE = re.compile(r"^<ide_opened_file>.*?</ide_opened_file>\s*", re.DOTALL)
ERR_TAG_RE = re.compile(r"</?tool_use_error>")
MAX = 140  # one-liner truncation width

NOISE_PREFIXES = (
    "Base directory for this skill:",
    "<command-message",
    "<command-name",
    "<command-args",
    "<local-command-stdout",
    "<local-command-stderr",
    "<local-command-caveat",
    "<env_context",
    "<environment_context",
    "<system-reminder",
    "<task-notification",
    "[SYSTEM NOTIFICATION - NOT USER INPUT]",
    "<bash-stdout",
    "<bash-stderr",
    "[Request interrupted by user",
    "<<autonomous-loop",
    "Caveat: The messages below were generated by the user while running local commands",
)

# Tools whose salient argument is a file path, not a description.
FILE_TOOLS = {"Edit", "Write", "Read", "NotebookEdit", "MultiEdit"}
# Fallback fields to summarize a tool call by, in priority order.
SALIENT_KEYS = ("command", "prompt", "query", "url", "path", "file_path", "message", "skill")


def short(s) -> str:
    s = " ".join(str(s).split())
    return s if len(s) <= MAX else s[: MAX - 1] + "…"


def clean_name(name: str) -> str:
    # mcp__server__tool -> tool (the server prefix is noise for a reader).
    return name.split("__")[-1] if name.startswith("mcp__") else name


def summarize_tool(name: str, inp) -> str | None:
    """One compact line for a tool call, or None to omit it entirely."""
    inp = inp if isinstance(inp, dict) else {}
    if name == "AskUserQuestion":
        return None  # captured separately as a user "[decision]" line
    if name in FILE_TOOLS:
        return f"{name} {inp.get('file_path') or inp.get('notebook_path') or '?'}"
    if name == "Skill":
        return f"Skill {inp.get('skill', '?')}"
    disp = clean_name(name)
    if inp.get("description"):  # human-written summary beats raw args (e.g. Bash)
        return f"{disp}: {short(inp['description'])}"
    for k in SALIENT_KEYS:
        if inp.get(k):
            return f"{disp}: {short(inp[k])}"
    return disp


def extract_text(content) -> str:
    """Pull user-visible text out of a message.content (string or list of blocks)."""
    if isinstance(content, str):
        return content.strip()
    if not isinstance(content, list):
        return ""
    chunks = [i.get("text", "") for i in content if isinstance(i, dict) and i.get("type") == "text"]
    return "\n".join(c for c in chunks if c).strip()


def tool_use_blocks(content) -> list[dict]:
    if not isinstance(content, list):
        return []
    return [b for b in content if isinstance(b, dict) and b.get("type") == "tool_use"]


def is_only_tool_result(content) -> bool:
    """True if a user message body is purely tool result echoes (no real text)."""
    if not isinstance(content, list):
        return False
    has_any = False
    for item in content:
        if not isinstance(item, dict):
            continue
        has_any = True
        if item.get("type") != "tool_result":
            return False
    return has_any


def error_map(content) -> dict:
    """tool_use_id -> short error text, for is_error tool_results in this message."""
    out = {}
    if not isinstance(content, list):
        return out
    for b in content:
        if not (isinstance(b, dict) and b.get("type") == "tool_result" and b.get("is_error")):
            continue
        c = b.get("content")
        if isinstance(c, list):
            c = " ".join(x.get("text", "") for x in c if isinstance(x, dict))
        out[b.get("tool_use_id")] = short(ERR_TAG_RE.sub("", str(c or "")).strip())
    return out


def decisions(record: dict) -> list[str]:
    """AskUserQuestion answers as 'question → answer' lines, from toolUseResult."""
    tur = record.get("toolUseResult")
    answers = tur.get("answers") if isinstance(tur, dict) else None
    if not isinstance(answers, dict):
        return []
    return [f"{q} → {a}" for q, a in answers.items()]


def is_noise(text: str) -> bool:
    if not text:
        return True
    return any(text.startswith(p) for p in NOISE_PREFIXES)


def distill(src: Path) -> dict:
    # ponytail: whole file buffered so errors (which arrive after their tool_use)
    # can be paired back. Session logs are small; stream + 2-pass if they balloon.
    records = []
    with src.open(encoding="utf-8") as f:
        for raw in f:
            try:
                records.append(json.loads(raw))
            except Exception:
                continue

    errors: dict = {}
    for d in records:
        m = d.get("message")
        if isinstance(m, dict):
            errors.update(error_map(m.get("content")))

    messages: list[dict] = []
    for d in records:
        if d.get("type") not in ("user", "assistant"):
            continue
        msg = d.get("message")
        if not isinstance(msg, dict):
            continue
        role = msg.get("role")
        if role not in ("user", "assistant"):
            continue
        content = msg.get("content", "")

        if role == "user":
            for line in decisions(d):  # keep decisions even from tool_result-only bodies
                messages.append({"role": "user", "text": f"[decision] {line}"})
            if is_only_tool_result(content):
                continue
            text = IDE_FILE_RE.sub("", extract_text(content)).strip()
            if text and not is_noise(text):
                messages.append({"role": "user", "text": text})
            continue

        # assistant: prose verbatim + tool calls reduced to one-line actions
        actions = []
        for b in tool_use_blocks(content):
            line = summarize_tool(b.get("name", ""), b.get("input"))
            if line is None:
                continue
            if b.get("id") in errors:
                line += f"  → error: {errors[b['id']]}"
            actions.append(line)
        entry = {"role": "assistant"}
        text = extract_text(content)
        if text:
            entry["text"] = text
        if actions:
            entry["actions"] = actions
        if len(entry) > 1:
            messages.append(entry)

    return {"source": src.name, "messages": messages}


def main() -> None:
    src, dst = Path(sys.argv[1]), Path(sys.argv[2])
    out = distill(src)
    dst.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {dst} ({dst.stat().st_size:,} bytes, {len(out['messages'])} messages)")


if __name__ == "__main__":
    main()
