#!/usr/bin/env python3
"""Clean a Claude Code session JSONL into a compact JSON conversation log.

Same output schema as `clean_codex_rollout.py`:
{
  "source": "<source file name>",
  "messages": [
    {"role": "user" | "assistant", "text": "..."},
    ...
  ]
}

Drops:
- Non-message record types (system, attachment, custom-title, etc.).
- Tool calls (tool_use) and tool results (tool_result blocks; user messages that
  contain only tool_result blocks are skipped entirely).
- Assistant `thinking` blocks.
- User messages that are harness-injected boilerplate: skill loads
  ("Base directory for this skill:"), <command-message>, <local-command-stdout>,
  <env_context>, <system-reminder>, <task-notification>, "Caveat:" sandbox notes,
  "[Request interrupted by user ...]", "<<autonomous-loop...>>" /loop sentinel.
- Strips leading <ide_opened_file>...</ide_opened_file> wrappers from user
  messages while keeping the real prose that follows.

Keeps:
- Real user `text` (or string) content.
- Real assistant `text` content (any thinking/tool_use is stripped, leaving
  only the user-visible response).

Usage: clean_claude_session.py SRC.jsonl DST.json
"""
import json
import re
import sys
from pathlib import Path

IDE_FILE_RE = re.compile(r"^<ide_opened_file>.*?</ide_opened_file>\s*", re.DOTALL)

SRC = Path(sys.argv[1])
DST = Path(sys.argv[2])

NOISE_PREFIXES = (
    "Base directory for this skill:",
    "<command-message",
    "<command-name",
    "<command-args",
    "<local-command-stdout",
    "<local-command-stderr",
    "<local-command-caveat",
    "<env_context",
    "<environment_context",
    "<system-reminder",
    "<task-notification",
    "[SYSTEM NOTIFICATION - NOT USER INPUT]",
    "<bash-stdout",
    "<bash-stderr",
    "[Request interrupted by user",
    "<<autonomous-loop",
    "Caveat: The messages below were generated by the user while running local commands",
)


def extract_text(content) -> str:
    """Pull user-visible text out of a message.content (string or list of blocks)."""
    if isinstance(content, str):
        return content.strip()
    if not isinstance(content, list):
        return ""
    chunks: list[str] = []
    for item in content:
        if not isinstance(item, dict):
            continue
        t = item.get("type")
        if t == "text":
            chunks.append(item.get("text", ""))
    return "\n".join(c for c in chunks if c).strip()


def is_only_tool_result(content) -> bool:
    """True if a user message body is purely tool result echoes (no real text)."""
    if not isinstance(content, list):
        return False
    has_any = False
    for item in content:
        if not isinstance(item, dict):
            continue
        has_any = True
        if item.get("type") != "tool_result":
            return False
    return has_any


def is_noise(text: str) -> bool:
    if not text:
        return True
    return any(text.startswith(p) for p in NOISE_PREFIXES)


def main() -> None:
    messages: list[dict] = []

    with SRC.open(encoding="utf-8") as f:
        for raw in f:
            try:
                d = json.loads(raw)
            except Exception:
                continue
            t = d.get("type")
            if t not in ("user", "assistant"):
                continue
            msg = d.get("message")
            if not isinstance(msg, dict):
                continue
            role = msg.get("role")
            if role not in ("user", "assistant"):
                continue

            content = msg.get("content", "")
            if role == "user" and is_only_tool_result(content):
                continue

            text = extract_text(content)
            if role == "user":
                # Strip leading <ide_opened_file>...</ide_opened_file> wrappers;
                # real user prose typically follows on the next line.
                text = IDE_FILE_RE.sub("", text).strip()
            if not text:
                continue
            if role == "user" and is_noise(text):
                continue

            messages.append({"role": role, "text": text})

    out = {"source": SRC.name, "messages": messages}
    DST.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {DST} ({DST.stat().st_size:,} bytes, {len(messages)} messages)")


if __name__ == "__main__":
    main()
