import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "clean_claude_session.py"

NOISE_PREFIXES = [
    "Base directory for this skill: /foo",
    "<command-message>/foo",
    "<command-name>bar",
    "<command-args>baz",
    "<local-command-stdout>output",
    "<local-command-stderr>err",
    "<local-command-caveat>caveat",
    "<env_context>cwd",
    "<environment_context>full",
    "<system-reminder>noise",
    "<task-notification>task",
    "[SYSTEM NOTIFICATION - NOT USER INPUT] something",
    "<bash-stdout>out",
    "<bash-stderr>err",
    "[Request interrupted by user for tool use]",
    "<<autonomous-loop-dynamic>>",
    "Caveat: The messages below were generated by the user while running local commands",
]


def run_script(src: Path, dst: Path) -> None:
    subprocess.run(
        [sys.executable, str(SCRIPT), str(src), str(dst)],
        capture_output=True, text=True, check=True,
    )


def write_jsonl(path: Path, records: list[dict]) -> None:
    path.write_text("\n".join(json.dumps(r) for r in records), encoding="utf-8")


def msg(role: str, content) -> dict:
    return {"type": role, "message": {"role": role, "content": content}}


def test_user_and_assistant_text_kept(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("user", "hello"),
        msg("assistant", [{"type": "text", "text": "hi"}]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [
        {"role": "user", "text": "hello"},
        {"role": "assistant", "text": "hi"},
    ]


def test_tool_use_reduced_to_action_line(tmp_path: Path) -> None:
    # prose and tool activity are separate entries (activity flushes at prose/EOF)
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "text", "text": "calling tool"},
            {"type": "tool_use", "id": "t1", "name": "Read",
             "input": {"file_path": "src/foo.py"}},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [
        {"role": "assistant", "text": "calling tool"},
        {"role": "assistant", "actions": ["Read src/foo.py"]},
    ]


def test_consecutive_reads_collapse_across_turns(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    # 3 browser calls, each its own assistant turn with a tool_result echo between
    recs = []
    for i in range(3):
        recs.append(msg("assistant", [
            {"type": "tool_use", "id": f"b{i}", "name": "mcp__claude-in-chrome__computer",
             "input": {"action": "left_click"}}]))
        recs.append(msg("user", [{"type": "tool_result", "tool_use_id": f"b{i}", "content": "ok"}]))
    write_jsonl(src, recs)
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "actions": ["browser ×3"]}]


def test_meta_tools_dropped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "tool_use", "id": "s1", "name": "ScheduleWakeup", "input": {"delaySeconds": 60}},
            {"type": "tool_use", "id": "m1", "name": "mcp__ccd_session__mark_chapter",
             "input": {"title": "next"}},
            {"type": "text", "text": "done"},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "done"}]


def test_skill_keeps_name_only(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [{"type": "tool_use", "id": "k1", "name": "Skill",
                           "input": {"skill": "ponytail"}}]),
        # harness injects the skill body as a noise user message — must be dropped
        msg("user", "Base directory for this skill: /foo/bar\n<full skill body...>"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "actions": ["Skill ponytail"]}]


def test_sync_subagent_result_kept_full(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    report = "Findings: the bug is in auth.py line 42, a missing null check. " * 5
    write_jsonl(src, [
        msg("assistant", [{"type": "tool_use", "id": "a1", "name": "Agent",
                           "input": {"description": "hunt the bug", "prompt": "..."}}]),
        msg("user", [{"type": "tool_result", "tool_use_id": "a1",
                      "content": [{"type": "text", "text": report}]}]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [
        {"role": "assistant", "actions": ["Agent: hunt the bug"]},
        {"role": "subagent", "text": report.strip()},
    ]


def test_async_subagent_stub_is_line_only(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [{"type": "tool_use", "id": "a1", "name": "Agent",
                           "input": {"description": "bg task", "prompt": "..."}}]),
        {"type": "user",
         "message": {"role": "user", "content": [
             {"type": "tool_result", "tool_use_id": "a1",
              "content": [{"type": "text", "text": "Async agent launched successfully."}]}]},
         "toolUseResult": {"isAsync": True, "agentId": "x"}},
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "actions": ["Agent: bg task"]}]


def test_readonly_bash_collapses_mutating_bash_kept(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [{"type": "tool_use", "id": "r1", "name": "Bash",
                           "input": {"command": "ls -la"}}]),
        msg("user", [{"type": "tool_result", "tool_use_id": "r1", "content": "files"}]),
        msg("assistant", [{"type": "tool_use", "id": "r2", "name": "Bash",
                           "input": {"command": "grep foo bar"}}]),
        msg("user", [{"type": "tool_result", "tool_use_id": "r2", "content": "hit"}]),
        msg("assistant", [{"type": "tool_use", "id": "w1", "name": "Bash",
                           "input": {"command": "rm -rf build", "description": "clean build"}}]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    # two read-only bashes collapse; the mutating one stays as its own line
    assert data["messages"] == [
        {"role": "assistant", "actions": ["bash(ro) ×2", "Bash: clean build"]},
    ]


def test_bash_summarized_by_description(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "tool_use", "id": "t1", "name": "Bash",
             "input": {"command": "pytest -q && echo done", "description": "Run tests"}},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "actions": ["Bash: Run tests"]}]


def test_tool_error_annotated_on_action(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "tool_use", "id": "t1", "name": "Write",
             "input": {"file_path": "a.py", "content": "x"}},
        ]),
        msg("user", [
            {"type": "tool_result", "tool_use_id": "t1", "is_error": True,
             "content": "<tool_use_error>File has not been read yet.</tool_use_error>"},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [
        {"role": "assistant",
         "actions": ["Write a.py  → error: File has not been read yet."]},
    ]


def test_ask_user_question_decision_kept(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    # The answer arrives as a tool_result-only user message carrying toolUseResult.
    user_answer = {
        "type": "user",
        "message": {"role": "user", "content": [
            {"type": "tool_result", "tool_use_id": "t1",
             "content": 'Your questions have been answered.'},
        ]},
        "toolUseResult": {"answers": {"Login blocker": "Build an offline demo"}},
    }
    write_jsonl(src, [
        msg("assistant", [
            {"type": "tool_use", "id": "t1", "name": "AskUserQuestion",
             "input": {"questions": [{"question": "Login blocker", "options": []}]}},
        ]),
        user_answer,
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    # assistant AskUserQuestion tool_use produces no action; decision is kept.
    assert data["messages"] == [
        {"role": "user", "text": "[decision] Login blocker → Build an offline demo"},
    ]


def test_tool_result_only_user_message_dropped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("user", [{"type": "tool_result", "tool_use_id": "t1", "content": "output"}]),
        msg("user", "real prompt"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "real prompt"}]


def test_thinking_blocks_dropped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "thinking", "thinking": "reasoning here"},
            {"type": "text", "text": "answer"},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "answer"}]


@pytest.mark.parametrize("noise", NOISE_PREFIXES)
def test_noise_prefix_dropped(tmp_path: Path, noise: str) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("user", noise),
        msg("user", "real prompt"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "real prompt"}]


def test_assistant_noise_prefix_not_filtered(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [{"type": "text", "text": "<system-reminder>still kept"}]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "<system-reminder>still kept"}]


def test_ide_file_wrapper_stripped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("user", "<ide_opened_file>foo.py</ide_opened_file>\nactual question"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "actual question"}]


def test_malformed_line_skipped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    src.write_text(
        json.dumps(msg("user", "first")) + "\n"
        "not valid json\n"
        + json.dumps(msg("user", "second")) + "\n",
        encoding="utf-8",
    )
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert [m["text"] for m in data["messages"]] == ["first", "second"]


def test_non_message_types_ignored(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        {"type": "system", "message": {"role": "system", "content": "ignored"}},
        {"type": "summary", "message": {"role": "user", "content": "ignored too"}},
        msg("user", "kept"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "kept"}]


def test_multiple_text_blocks_concatenated(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "text", "text": "part 1"},
            {"type": "text", "text": "part 2"},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "part 1\npart 2"}]


def test_unicode_text_preserved(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [msg("user", "مرحبا 👋 héllo")])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "مرحبا 👋 héllo"}]


def test_reads_utf8_under_non_utf8_locale(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [msg("user", "مرحبا 👋 héllo")])
    env = {**os.environ, "PYTHONUTF8": "0", "LC_ALL": "C", "LANG": "C"}
    subprocess.run(
        [sys.executable, str(SCRIPT), str(src), str(dst)],
        env=env, capture_output=True, text=True, check=True,
    )
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "مرحبا 👋 héllo"}]


def test_empty_input_file(tmp_path: Path) -> None:
    src = tmp_path / "empty.jsonl"
    dst = tmp_path / "out.json"
    src.write_text("", encoding="utf-8")
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data == {"source": "empty.jsonl", "messages": []}


def test_output_schema(tmp_path: Path) -> None:
    src = tmp_path / "session.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [msg("user", "hi")])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["source"] == "session.jsonl"
    assert isinstance(data["messages"], list)
    assert set(data.keys()) == {"source", "messages"}
