import json
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "clean_claude_session.py"

NOISE_PREFIXES = [
    "Base directory for this skill: /foo",
    "<command-message>/foo",
    "<command-name>bar",
    "<command-args>baz",
    "<local-command-stdout>output",
    "<local-command-stderr>err",
    "<local-command-caveat>caveat",
    "<env_context>cwd",
    "<environment_context>full",
    "<system-reminder>noise",
    "<task-notification>task",
    "[SYSTEM NOTIFICATION - NOT USER INPUT] something",
    "<bash-stdout>out",
    "<bash-stderr>err",
    "[Request interrupted by user for tool use]",
    "<<autonomous-loop-dynamic>>",
    "Caveat: The messages below were generated by the user while running local commands",
]


def run_script(src: Path, dst: Path) -> None:
    subprocess.run(
        [sys.executable, str(SCRIPT), str(src), str(dst)],
        capture_output=True, text=True, check=True,
    )


def write_jsonl(path: Path, records: list[dict]) -> None:
    path.write_text("\n".join(json.dumps(r) for r in records), encoding="utf-8")


def msg(role: str, content) -> dict:
    return {"type": role, "message": {"role": role, "content": content}}


def test_user_and_assistant_text_kept(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("user", "hello"),
        msg("assistant", [{"type": "text", "text": "hi"}]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [
        {"role": "user", "text": "hello"},
        {"role": "assistant", "text": "hi"},
    ]


def test_tool_use_blocks_dropped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "text", "text": "calling tool"},
            {"type": "tool_use", "id": "t1", "name": "Read", "input": {}},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "calling tool"}]


def test_assistant_with_only_tool_use_dropped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [{"type": "tool_use", "id": "t1", "name": "Read", "input": {}}]),
        msg("assistant", [{"type": "text", "text": "real reply"}]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "real reply"}]


def test_tool_result_only_user_message_dropped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("user", [{"type": "tool_result", "tool_use_id": "t1", "content": "output"}]),
        msg("user", "real prompt"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "real prompt"}]


def test_thinking_blocks_dropped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "thinking", "thinking": "reasoning here"},
            {"type": "text", "text": "answer"},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "answer"}]


@pytest.mark.parametrize("noise", NOISE_PREFIXES)
def test_noise_prefix_dropped(tmp_path: Path, noise: str) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("user", noise),
        msg("user", "real prompt"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "real prompt"}]


def test_assistant_noise_prefix_not_filtered(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [{"type": "text", "text": "<system-reminder>still kept"}]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "<system-reminder>still kept"}]


def test_ide_file_wrapper_stripped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("user", "<ide_opened_file>foo.py</ide_opened_file>\nactual question"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "actual question"}]


def test_malformed_line_skipped(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    src.write_text(
        json.dumps(msg("user", "first")) + "\n"
        "not valid json\n"
        + json.dumps(msg("user", "second")) + "\n",
        encoding="utf-8",
    )
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert [m["text"] for m in data["messages"]] == ["first", "second"]


def test_non_message_types_ignored(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        {"type": "system", "message": {"role": "system", "content": "ignored"}},
        {"type": "summary", "message": {"role": "user", "content": "ignored too"}},
        msg("user", "kept"),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "kept"}]


def test_multiple_text_blocks_concatenated(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [
        msg("assistant", [
            {"type": "text", "text": "part 1"},
            {"type": "text", "text": "part 2"},
        ]),
    ])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "assistant", "text": "part 1\npart 2"}]


def test_unicode_text_preserved(tmp_path: Path) -> None:
    src = tmp_path / "in.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [msg("user", "مرحبا 👋 héllo")])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["messages"] == [{"role": "user", "text": "مرحبا 👋 héllo"}]


def test_empty_input_file(tmp_path: Path) -> None:
    src = tmp_path / "empty.jsonl"
    dst = tmp_path / "out.json"
    src.write_text("", encoding="utf-8")
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data == {"source": "empty.jsonl", "messages": []}


def test_output_schema(tmp_path: Path) -> None:
    src = tmp_path / "session.jsonl"
    dst = tmp_path / "out.json"
    write_jsonl(src, [msg("user", "hi")])
    run_script(src, dst)
    data = json.loads(dst.read_text(encoding="utf-8"))
    assert data["source"] == "session.jsonl"
    assert isinstance(data["messages"], list)
    assert set(data.keys()) == {"source", "messages"}
